# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e56855f068d35fe1fc96e73bf90ae937"
name = "Attribix"
handle = "attribix-app"

application_url = "https://attribix-app.fly.dev/app"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders_create"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "read_customers,read_orders,read_products,read_script_tags,write_pixels,write_products,write_script_tags"

[auth]
redirect_urls = [
  "https://attribix-app.fly.dev/auth/callback",
  "https://attribix-app.fly.dev/auth/login",
  "https://attribix-app.fly.dev/auth"
]

[app_proxy]
url = "https://attribix-app.fly.dev/pixel.js"
subpath = "pixel"
prefix = "apps"

[pos]
embedded = false
